### ISSUE TITLE
Refactor CatWatcher to make some semblance of sense

### ISSUE THREAD

**Issue by stwalkerster** [helpmebot/helpmebot#168]
```[tasklist]
### Tasks
- [x] Rip out item persistence
- [ ] https://github.com/helpmebot/helpmebot/issues/172
- [x] Rip out list comparison
- [ ] https://github.com/helpmebot/helpmebot/issues/171
- [x] Unify the forced + scheduled updates in some way
```
